# Generated by Django 4.2.13 on 2024-06-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AL', 'Alimentação'), ('CO', 'Combustível'), ('PE', 'Pedágio/Estacionamento')], max_length=2)),
                ('valor_nota', models.FloatField()),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
    ]
