# Generated by Django 4.2.13 on 2024-06-25 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('destino', models.CharField(max_length=100)),
                ('veiculo', models.CharField(max_length=10)),
                ('km_inicial', models.FloatField()),
                ('km_final', models.FloatField(blank=True, null=True)),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10)),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='nota',
            name='data_nota',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('AL', 'Alimentação'), ('CO', 'Combustível'), ('PE', 'Pedágio'), ('ES', 'Estacionamento'), ('NO', 'Nome'), ('HO', 'Hospedagem'), ('OU', 'Outros')], max_length=2),
        ),
        migrations.AddField(
            model_name='nota',
            name='viagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='notas.viagem'),
            preserve_default=False,
        ),
    ]
