# Generated by Django 4.2.13 on 2024-06-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_viagem_nota_anexo_nota_data_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('Iniciada', 'Iniciada'), ('Finalizada', 'Finalizada')], default='Iniciada', max_length=10),
        ),
    ]
