# Generated by Django 4.2.13 on 2024-06-26 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notas', '0003_viagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='aprovadores',
            field=models.ManyToManyField(blank=True, related_name='notas_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Revisão', 'Em Revisão'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='status',
            field=models.CharField(choices=[('Iniciada', 'Iniciada'), ('Finalizada', 'Finalizada'), ('Em Revisão', 'Em Revisão'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Iniciada', max_length=10),
        ),
    ]
