# Generated by Django 4.2.13 on 2024-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_nota_aprovadores_nota_status_alter_viagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
