# Generated by Django 4.2.13 on 2024-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_nota_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='aprovadores',
        ),
        migrations.AlterField(
            model_name='nota',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Reprovada', 'Reprovada')], default='Pendente', max_length=10),
        ),
    ]
